const options = {
	hobbies: [
		{ value: "anime", label: "Anime" },
		{ value: "gaming", label: "Gaming" },
		{ value: "gamma_rad", label: "Gamma Radiation" },
		{ value: "hiking", label: "Hiking" },
		{ value: "camping", label: "Camping" },
		{ value: "running", label: "Running" },
		{ value: "Archery", label: "Archery" },
		{ value: "Parkour", label: "Parkour" },
		{ value: "Astronomy", label: "Astronomy" },
		{ value: "Kite Flying", label: "Kite Flying" },
		{ value: "Stamp Collecting", label: "Stamp Collecting" },
		{ value: "Art Collecting", label: "Art Collecting" },
		{ value: "Cooking", label: "Cooking" },
		{ value: "Baking", label: "Baking" },
		{ value: "Sewing", label: "Sewing" },
		{ value: "Sleeping", label: "Sleeping" },
		{ value: "Painting", label: "Painting" },
		{ value: "Drawing", label: "Drawing" },
		{ value: "Origami", label: "Origami" },
		{ value: "Photography", label: "Photography" },
		{ value: "Board Games", label: "Board Games" },
		{ value: "Card Games", label: "Card Games" },
		{ value: "Chess", label: "Chess" },
		{ value: "Puzzles", label: "Puzzles" },
		{ value: "Juggling", label: "Juggling" },
		{ value: "Podcast", label: "Podcast" },
		{ value: "Makeup", label: "Makeup" },
		{ value: "Dancing", label: "Dancing" },
		{ value: "Coding", label: "Coding" },
		{ value: "Cars", label: "Cars" },
	],
	courses: [
		{ value: "csc490", label: "CSC490" },
		{ value: "csc420", label: "CSC420" },
		{ value: "csc318", label: "CSC318" },
		{ value: "csc343", label: "CSC343" },
		{ value: "csc301", label: "CSC301" },
		{ value: "csc309", label: "CSC309" },
		{ value: "csc347", label: "CSC347" },
		{ value: "csc369", label: "CSC369" },
		{ value: "csc373", label: "CSC373" },
		{ value: "csc311", label: "CSC311" },
		{ value: "csc258", label: "CSC258" },
		{ value: "csc263", label: "CSC263" },
		{ value: "csc209", label: "CSC209" },
		{ value: "csc236", label: "CSC236" },
		{ value: "csc207", label: "CSC207" },
		{ value: "csc148", label: "CSC148" },
		{ value: "csc108", label: "CSC108" },
		{ value: "cct110", label: "CCT110" },
		{ value: "cct109", label: "CCT109" },
	],
};

export default options;
